'use client'

import { useEffect, useState } from 'react'
import { BrowserRouter, Routes, Route, Link, useLocation } from 'react-router-dom'
import { ArrowUpRight, GitBranch, Menu, X, Code2, Database, Smartphone, Mail, MapPin, Send, CheckCircle2 } from 'lucide-react'

const projects = [
  { title: 'Personal Portfolio', description: 'A responsive portfolio experience designed to make a clear, confident first impression.', techStack: ['React', 'JavaScript', 'CSS'], image: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=1200&q=80', link: 'https://example.com' },
  { title: 'Task Management App', description: 'A focused productivity tool with intuitive task flows, filters, and thoughtful empty states.', techStack: ['React', 'Local Storage', 'CSS'], image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80', link: 'https://example.com' },
  { title: 'Weather Dashboard', description: 'A clean dashboard that turns live forecast data into a quick, useful daily snapshot.', techStack: ['React', 'REST API', 'Responsive UI'], image: 'https://images.unsplash.com/photo-1499346030926-9a72daac6c63?auto=format&fit=crop&w=1200&q=80', link: 'https://example.com' },
]

const skills = [
  { icon: Code2, name: 'Frontend', text: 'HTML, CSS, JavaScript, React' },
  { icon: Database, name: 'Backend basics', text: 'REST APIs, data flow, JSON' },
  { icon: Smartphone, name: 'Responsive design', text: 'Mobile-first interfaces that scale' },
  { icon: GitBranch, name: 'Developer workflow', text: 'Git, GitHub, reusable components' },
]

function Navbar() {
  const [open, setOpen] = useState(false)
  const location = useLocation()
  const links = [['/', 'Home'], ['/about', 'About'], ['/projects', 'Projects'], ['/contact', 'Contact']]
  return <header className="site-header"><nav className="nav-wrap" aria-label="Main navigation"><Link to="/" className="brand" onClick={() => setOpen(false)}><span className="brand-mark">NM</span><span>Nimra Mushtaq</span></Link><button className="menu-toggle" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><div className={`nav-links ${open ? 'is-open' : ''}`}>{links.map(([href, label]) => <Link key={href} to={href} className={location.pathname === href ? 'active' : ''} onClick={() => setOpen(false)}>{label}</Link>)}<Link className="nav-cta" to="/contact" onClick={() => setOpen(false)}>Let&apos;s talk <ArrowUpRight size={15} /></Link></div></nav></header>
}

function Hero() { return <section className="hero section-shell"><div className="hero-copy"><p className="eyebrow fade-up">Available for new opportunities <span className="status-dot" /></p><h1 className="fade-up delay-1">Building digital<br /><em>experiences</em> with intent.</h1><p className="hero-lede fade-up delay-2">Hi, I&apos;m <strong>Nimra Mushtaq</strong> — a frontend developer turning thoughtful ideas into fast, accessible, and beautifully crafted web applications.</p><div className="hero-actions fade-up delay-3"><Link className="button button-primary" to="/projects">View my projects <ArrowUpRight size={17} /></Link><Link className="button button-quiet" to="/contact">Contact me <span>↗</span></Link></div><div className="social-row fade-up delay-3"><a href="https://github.com" target="_blank" rel="noreferrer"><GitBranch size={17} /> GitHub</a><a href="https://linkedin.com" target="_blank" rel="noreferrer"><GitBranch size={17} /> LinkedIn</a></div></div><div className="hero-visual" aria-label="Abstract developer workspace illustration"><div className="visual-grid" /><div className="code-card"><div className="code-top"><span /><span /><span /><small>nimra.dev</small></div><pre><code><span className="code-muted">const</span> <span className="code-blue">developer</span> = {'{'}{`\n`}  name: <span className="code-gold">&quot;Nimra&quot;</span>,{`\n`}  focus: <span className="code-gold">&quot;the web&quot;</span>,{`\n`}  passion: <span className="code-gold">true</span>{`\n`}{'}'}</code></pre></div><div className="visual-caption"><span>01 / 04</span><span>Crafting with purpose</span></div></div></section> }

function AboutSection() { return <section className="section-shell about-section"><div className="section-label">01 <span>About me</span></div><div className="about-layout"><div><h2>A curious mind with a<br /><em>practical point of view.</em></h2></div><div className="about-copy"><p>I&apos;m a student and developer who enjoys the space where design meets technology. I care about the details that make an interface feel clear, responsive, and genuinely useful.</p><p>My journey started with the fundamentals and grew through hands-on projects, experiments, and a lot of curiosity. Today, I&apos;m focused on building an adaptable toolkit for the modern web.</p><Link className="text-link" to="/about">More about my journey <ArrowUpRight size={16} /></Link></div></div><div className="stats-grid"><div><strong>10<span>+</span></strong><small>Projects built</small></div><div><strong>5<span>+</span></strong><small>Core technologies</small></div><div><strong>1<span>+</span></strong><small>Year learning</small></div><div><strong>100<span>%</span></strong><small>Curiosity</small></div></div></section> }

function SkillsSection() { return <section className="section-shell skills-section"><div className="section-label">02 <span>What I work with</span></div><div className="section-heading"><h2>Tools for turning<br /><em>thoughts into things.</em></h2><p>A growing, practical toolkit built around strong fundamentals and a love for learning new ways to solve problems.</p></div><div className="skills-grid">{skills.map(({ icon: Icon, name, text }) => <div className="skill-card" key={name}><Icon size={22} strokeWidth={1.5} /><h3>{name}</h3><p>{text}</p><span className="card-arrow">↗</span></div>)}</div></section> }

function ProjectCard({ project, index }: { project: typeof projects[number], index: number }) { return <article className="project-card"><a href={project.link} target="_blank" rel="noreferrer" className="project-image"><img src={project.image} alt={`${project.title} project preview`} /><span className="project-number">0{index + 1}</span><span className="image-arrow"><ArrowUpRight size={19} /></span></a><div className="project-info"><h3>{project.title}</h3><p>{project.description}</p><div className="tech-list">{project.techStack.map((tech) => <span key={tech}>{tech}</span>)}</div><div className="project-links"><a href={project.link} target="_blank" rel="noreferrer">Live demo <ArrowUpRight size={15} /></a><a href="https://github.com" target="_blank" rel="noreferrer"><GitBranch size={15} /> Source</a></div></div></article> }

function ProjectsSection() { return <section className="section-shell projects-section"><div className="section-label">03 <span>Selected work</span></div><div className="section-heading project-heading"><h2>A few things I&apos;ve<br /><em>made along the way.</em></h2><Link className="text-link" to="/projects">View all projects <ArrowUpRight size={16} /></Link></div><div className="projects-grid">{projects.map((project, index) => <ProjectCard project={project} index={index} key={project.title} />)}</div></section> }

function ContactForm() { const [form, setForm] = useState({ name: '', email: '', message: '' }); const [sent, setSent] = useState(false); const submit = (e: React.FormEvent) => { e.preventDefault(); if (!form.name || !form.email || !form.message) return; console.log('[v0] Contact form submitted:', form); setSent(true); setForm({ name: '', email: '', message: '' }) }; return <form className="contact-form" onSubmit={submit}><label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Message<textarea required value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} placeholder="Tell me a little about your idea..." rows={4} /></label><button className="button button-primary" type="submit">Send message <Send size={16} /></button>{sent && <p className="success-message"><CheckCircle2 size={16} /> Thanks — I&apos;ll be in touch soon.</p>}</form> }

function ContactSection() { return <section className="section-shell contact-section"><div className="section-label">04 <span>Get in touch</span></div><div className="contact-layout"><div><h2>Have a project<br /><em>in mind?</em></h2><p className="contact-intro">I&apos;m always open to new conversations, thoughtful collaborations, and interesting problems to solve.</p><div className="contact-details"><a href="mailto:nimra@example.com"><Mail size={17} /> nimra@example.com</a><span><MapPin size={17} /> Pakistan · Remote friendly</span></div></div><ContactForm /></div></section> }

function Footer() { return <footer className="footer"><div className="footer-top"><Link to="/" className="brand"><span className="brand-mark">NM</span><span>Nimra Mushtaq</span></Link><p>Building with curiosity, one interface at a time.</p><div className="footer-social"><a href="https://github.com" target="_blank" rel="noreferrer"><GitBranch size={18} /></a><a href="https://linkedin.com" target="_blank" rel="noreferrer"><GitBranch size={18} /></a></div></div><div className="footer-bottom"><span>© 2026 Nimra Mushtaq. All rights reserved.</span><span>Designed &amp; built with care.</span></div></footer> }

function Home() { return <><Hero /><AboutSection /><SkillsSection /><ProjectsSection /><ContactSection /></> }
function PageIntro({ title, eyebrow }: { title: string, eyebrow: string }) { return <section className="page-intro section-shell"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></section> }
function PortfolioApp() { return <BrowserRouter><Navbar /><main><Routes><Route path="/" element={<Home />} /><Route path="/about" element={<><PageIntro eyebrow="A little context" title="About Nimra" /><AboutSection /><SkillsSection /></>} /><Route path="/projects" element={<><PageIntro eyebrow="Selected work" title="Projects & experiments" /><ProjectsSection /></>} /><Route path="/contact" element={<><PageIntro eyebrow="Start a conversation" title="Let&apos;s make something useful." /><ContactSection /></>} /></Routes></main><Footer /></BrowserRouter> }

function App() { const [mounted, setMounted] = useState(false); useEffect(() => setMounted(true), []); return mounted ? <PortfolioApp /> : <main className="app-loading" aria-label="Loading portfolio" /> }

export default App
